# Site settings
title: Hawthorne Ghost Tour
email: marina@tourguideforhire.com
myname: Marina Martinez
description: > # this means to ignore newlines until "baseurl:"
  The Hawthorne Ghost Tour is a fun, exciting, and educational adventure through the heart of East Portland’s old red light district.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tourhawthorne.com/" # the base hostname & protocol for your site
twitter_username: tourhawthorne

# Outputting
permalink:     none

# Build settings
markdown: kramdown
ftp_host: 'marinarosemartinez.com'
ftp_dir: '/'
ftp_passive: false

# optional
ftp_port: 21                  # default 21
ftp_username: 'tourhawthorne@marinarosemartinez.com'     # default read from stdin
ftp_password: '.g.vdFx[m2v}' # default read from stdin