# Site settings
title: Tour Guide For Hire
email: marina@tourguideforhire.com
myname: Marina Martinez
description: > # this means to ignore newlines until "baseurl:"
  Guiding tours all around Portland, Oregon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tourguideforhire.com/" # the base hostname & protocol for your site
twitter_username: marinarmartinez

# Build settings
markdown: kramdown
ftp_host: 'tourguideforhire.com'
ftp_dir: '/'
ftp_passive: false

# optional
ftp_port: 21                  # default 21
ftp_username: 'tourguideforhire@marinarosemartinez.com'     # default read from stdin
ftp_password: 'wu[-}TCGr]=A' # default read from stdin