baseURL = "https://www.tourhawthorne.com/"
languageCode = "en-us"
title = "Tour Hawthorne"
theme = "ananke"

marina_phone = "714-675-1124"

[menu]

  [[menu.main]]
    identifier = "buy"
    name = "Buy Tickets"
    url = "https://www.eventbrite.com/e/hawthorne-ghost-tour-tickets-14917118503"